-- liquibase formatted sql

-- changeset root:1780309613015-1
CREATE TABLE DIP_LOG_JOB (ID_LOG_JOB NUMBER NOT NULL, NM_JOB VARCHAR2(100 BYTE) NOT NULL, TI_EVENTO VARCHAR2(20 BYTE) NOT NULL, DT_EVENTO TIMESTAMP(3) NOT NULL, DS_ERRORE VARCHAR2(1000 BYTE), CD_IND_SERVER VARCHAR2(100 BYTE), CONSTRAINT PK_LOG_JOB PRIMARY KEY (ID_LOG_JOB));

-- changeset root:1780309613015-2
CREATE TABLE DIP_PARAM_APPLIC (ID_PARAM_APPLIC NUMBER NOT NULL, NM_PARAM_APPLIC VARCHAR2(100 BYTE) NOT NULL, DS_PARAM_APPLIC VARCHAR2(254 BYTE) NOT NULL, DS_VALORE_PARAM_APPLIC VARCHAR2(254 BYTE) NOT NULL, TI_PARAM_APPLIC VARCHAR2(20 BYTE) NOT NULL, CONSTRAINT PK_PAR_APL PRIMARY KEY (ID_PARAM_APPLIC));

-- changeset root:1780309613015-3
CREATE OR REPLACE FORCE VIEW "MON_V_LIS_INI_SCHED_JOB" ("ID_LOG_JOB", "NM_JOB", "DT_REG_LOG_JOB_INI", "DT_REG_LOG_JOB_FINE_SUC", "DT_REG_LOG_JOB_INI_SUC") AS SELECT inizio_job.id_log_job,
           inizio_job.nm_job,
           inizio_job.dt_evento
               dt_reg_log_job_ini,
           (SELECT MIN (fine_job_min.dt_evento)
              FROM DIP_LOG_JOB fine_job_min
             WHERE fine_job_min.nm_job = inizio_job.nm_job
               AND fine_job_min.ti_evento IN ('FINE_ESECUZIONE', 'ERRORE')
               AND fine_job_min.dt_evento >= inizio_job.dt_evento)
               dt_reg_log_job_fine_suc,
           (SELECT MIN (inizio_suc.dt_evento)
              FROM DIP_LOG_JOB inizio_suc
             WHERE inizio_suc.nm_job = inizio_job.nm_job
               AND inizio_suc.ti_evento = 'INIZIO_ESECUZIONE'
               AND inizio_suc.dt_evento > inizio_job.dt_evento)
               dt_reg_log_job_ini_suc
      FROM DIP_LOG_JOB inizio_job
     WHERE inizio_job.ti_evento = 'INIZIO_ESECUZIONE';

-- changeset root:1780309613015-4
CREATE OR REPLACE FORCE VIEW "LOG_V_VIS_LAST_SCHED" ("ID_LOG_JOB", "NM_JOB", "DT_EVENTO_INI", "FL_JOB_ATTIVO", "LAST_EXEC_OK") AS SELECT MAX (tabl.id_log_job),
             tabl.nm_job,
             tabl.dt_evento_ini,
             tabl.fl_job_attivo,
             tabl.last_exec_ok
        FROM (SELECT inizio_job.id_log_job,
                     inizio_job.nm_job,
                     inizio_job.dt_evento    dt_evento_ini,
                     CASE
                         WHEN EXISTS
                                  (SELECT *
                                     FROM DIP_LOG_JOB fine_job
                                    WHERE fine_job.nm_job = inizio_job.nm_job
                                      AND fine_job.ti_evento IN
                                              ('FINE_ESECUZIONE', 'ERRORE')
                                      AND fine_job.dt_evento >=
                                          inizio_job.dt_evento) THEN
                             '0'
                         ELSE
                             '1'
                     END                     fl_job_attivo,
                     CASE
                         WHEN EXISTS
                                  (SELECT *
                                     FROM DIP_LOG_JOB fine_job
                                    WHERE fine_job.nm_job = inizio_job.nm_job
                                      AND fine_job.ti_evento IN
                                              ('FINE_ESECUZIONE')
                                      AND fine_job.dt_evento >=
                                          inizio_job.dt_evento) THEN
                             '1'
                         ELSE
                             '0'
                     END                     last_exec_ok
                FROM DIP_LOG_JOB inizio_job
               WHERE inizio_job.ti_evento = 'INIZIO_ESECUZIONE'
                 AND inizio_job.dt_evento =
                     (SELECT MAX (inizio_job_max.dt_evento)
                        FROM DIP_LOG_JOB inizio_job_max
                       WHERE inizio_job_max.nm_job = inizio_job.nm_job
                         AND inizio_job_max.ti_evento = 'INIZIO_ESECUZIONE'))
             tabl
    GROUP BY tabl.nm_job,
             tabl.dt_evento_ini,
             tabl.fl_job_attivo,
             tabl.last_exec_ok;

-- changeset root:1780309613015-5
COMMENT ON COLUMN LOG_V_VIS_LAST_SCHED.ID_LOG_JOB IS 'PK.1';

-- changeset root:1780309613015-6
CREATE OR REPLACE FORCE VIEW "APL_V_LOG_JOB" ("ID_LOG_JOB", "NM_JOB", "TI_REG_LOG_JOB", "DT_REG_LOG_JOB", "DL_MSG_ERR") AS SELECT ID_LOG_JOB, NM_JOB, TI_EVENTO, DT_EVENTO, DS_ERRORE    
  FROM DIP_LOG_JOB;

-- changeset root:1780309613015-7
CREATE OR REPLACE FORCE VIEW "APL_V_PARAM_APPLIC" ("NM_PARAM_APPLIC", "DS_PARAM_APPLIC", "DS_VALORE_PARAM_APPLIC", "TI_PARAM_APPLIC") AS select 
	nm_param_applic,
    ds_param_applic,
    ds_valore_param_applic,
    ti_param_applic
from DIP_PARAM_APPLIC par;

-- changeset root:1780309613015-8
CREATE OR REPLACE FORCE VIEW "MON_V_LIS_SCHED_JOB" ("ID_LOG_JOB", "NM_JOB", "DT_REG_LOG_JOB_INI", "DT_REG_LOG_JOB_FINE", "DURATA_GG", "DURATA_ORE", "DURATA_MIN", "DURATA_SEC", "DL_MSG_ERR") AS select
 tmp.id_log_job,
 tmp.nm_job,
 tmp.dt_reg_log_job_ini,
 
 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null)
		then tmp.dt_reg_log_job_fine_suc
		else null
 end dt_reg_log_job_fine,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then (SELECT EXTRACT( DAY    FROM difference ) AS days
                FROM   (
                  SELECT 
                           tmp1.dt_reg_log_job_fine_suc
                             - tmp1.dt_reg_log_job_ini
                            AS difference
                            FROM   MON_V_LIS_INI_SCHED_JOB tmp1
                            WHERE tmp1.id_log_job = tmp.id_log_job))
		else null
 end durata_gg,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then (SELECT EXTRACT( HOUR   FROM difference ) AS hours
                FROM   (
                  SELECT 
                           tmp1.dt_reg_log_job_fine_suc
                             - tmp1.dt_reg_log_job_ini
                            AS difference
                            FROM   MON_V_LIS_INI_SCHED_JOB tmp1
                            WHERE tmp1.id_log_job = tmp.id_log_job))
		else null
 end durata_ore,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then (SELECT EXTRACT( MINUTE FROM difference ) AS minutes
                FROM   (
                  SELECT 
                           tmp1.dt_reg_log_job_fine_suc
                             - tmp1.dt_reg_log_job_ini
                            AS difference
                            FROM   MON_V_LIS_INI_SCHED_JOB tmp1
                            WHERE tmp1.id_log_job = tmp.id_log_job))
		else null
 end durata_min,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then (SELECT trunc(EXTRACT( SECOND FROM difference )) as seconds 
                FROM   (
                  SELECT 
                           tmp1.dt_reg_log_job_fine_suc
                             - tmp1.dt_reg_log_job_ini
                            AS difference
                            FROM   MON_V_LIS_INI_SCHED_JOB tmp1
                            WHERE tmp1.id_log_job = tmp.id_log_job))
		else null
 end durata_sec,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then (select min(fine_job.ds_errore)
			from DIP_LOG_JOB fine_job 
			where fine_job.nm_job = tmp.nm_job
			and fine_job.ti_evento in ('FINE_ESECUZIONE', 'ERRORE')
			and fine_job.dt_evento = tmp.dt_reg_log_job_fine_suc)
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc < tmp.dt_reg_log_job_fine_suc)
		then 'Job terminato per caduta dell''application server'
		else null
 end dl_msg_err

from MON_V_LIS_INI_SCHED_JOB tmp;

-- changeset root:1780309613015-9
COMMENT ON COLUMN MON_V_LIS_SCHED_JOB.ID_LOG_JOB IS 'PK.1 relativa a tabella DIP_LOG_JOB';

-- changeset root:1780309613015-10
CREATE SEQUENCE SDIP_ATTRIB_RISULTATO START WITH 701 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-11
CREATE SEQUENCE SDIP_CAMPO_RICERCA START WITH 481 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-12
CREATE SEQUENCE SDIP_COMBINAZIONE_RICERCA START WITH 341 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-13
CREATE SEQUENCE SDIP_DEC_JOB START WITH 41 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-14
CREATE SEQUENCE SDIP_DEF_ATTRIBUTO START WITH 1341 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-15
CREATE SEQUENCE SDIP_ELEMENTO_DETTAGLIO START WITH 441 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-16
CREATE SEQUENCE SDIP_ELEMENTO_LISTA START WITH 381 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-17
CREATE SEQUENCE SDIP_FILTRO_RICERCA START WITH 1321 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-18
CREATE SEQUENCE SDIP_GRUPPO_CAMPI START WITH 221 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-19
CREATE SEQUENCE SDIP_GRUPPO_DETTAGLIO START WITH 181 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-20
CREATE SEQUENCE SDIP_LOG_JOB START WITH 3293 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-21
CREATE SEQUENCE SDIP_PARAM_APPLIC START WITH 181 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-22
CREATE SEQUENCE SDIP_QUERY_WITH START WITH 141 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-23
CREATE SEQUENCE SDIP_RICERCA START WITH 221 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-24
CREATE SEQUENCE SDIP_SERVER START WITH 381 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-25
CREATE SEQUENCE SDIP_SYNCRO_ARO START WITH 241 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-26
CREATE SEQUENCE SDIP_SYNCRO_CONF START WITH 21 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-27
CREATE SEQUENCE SDIP_TIPO_DATO_PROFILO START WITH 121 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-28
CREATE SEQUENCE SDIP_USO_WITH START WITH 201 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-29
CREATE SEQUENCE SDIP_VALORE_COMBO START WITH 9961 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-30
CREATE SEQUENCE SDIP_VALORE_PREDEFINITO START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-31
CREATE SEQUENCE SIAM_USER START WITH 41 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-32
CREATE SEQUENCE SRICERCA_PUG START WITH 81 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-33
CREATE SEQUENCE SSTRUT_REFERENZIATE_PUG START WITH 221 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-34
CREATE SEQUENCE SSTRUT_REFERENZIATE_PUGA START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1780309613015-35 splitStatements:true
CREATE TABLE DEC_JOB_FOTO (ID_JOB_FOTO NUMBER NOT NULL, NM_JOB_FOTO VARCHAR2(100 BYTE) NOT NULL, TI_SCHED_JOB_FOTO VARCHAR2(20 BYTE) NOT NULL, TI_SCOPO_JOB_FOTO VARCHAR2(40 BYTE) NOT NULL, NM_NODO_ASSEGNATO_FOTO VARCHAR2(100 BYTE), TI_STATO_TIMER_FOTO VARCHAR2(20 BYTE), CD_SCHED_HOUR_FOTO VARCHAR2(100 BYTE), CD_SCHED_MINUTE_FOTO VARCHAR2(100 BYTE), CD_SCHED_DAYOFMONTH_FOTO VARCHAR2(100 BYTE), CD_SCHED_MONTH_FOTO VARCHAR2(100 BYTE), CD_SCHED_DAYOFWEEK_FOTO VARCHAR2(100 BYTE), DT_PROSSIMA_ATTIVAZIONE_FOTO date, FL_DATA_ACCURATA_FOTO VARCHAR2(1 BYTE), DS_JOB_FOTO VARCHAR2(200 BYTE), NM_AMBITO_FOTO VARCHAR2(200 BYTE), NI_ORD_EXEC_FOTO NUMBER, DT_JOB_FOTO date, CONSTRAINT PK_JOB_FOTO PRIMARY KEY (ID_JOB_FOTO));
COMMENT ON TABLE DEC_JOB_FOTO IS 'Tabella per configurare l''esecuzione dei timer. Utilizzata dai job su jboss e dalle sonde Zabbix';
COMMENT ON COLUMN DEC_JOB_FOTO.NM_NODO_ASSEGNATO_FOTO IS 'Nome del nodo del cluster su cui verrà eseguito il job';
COMMENT ON COLUMN DEC_JOB_FOTO.TI_STATO_TIMER_FOTO IS 'Stato del job: ATTIVO, INATTIVO o ESECUZIONE_SINGOLA';
COMMENT ON COLUMN DEC_JOB_FOTO.CD_SCHED_HOUR_FOTO IS 'Campo ''ora'' nella schedulazione del job';
COMMENT ON COLUMN DEC_JOB_FOTO.CD_SCHED_MINUTE_FOTO IS 'Campo ''minuto'' nella schedulazione del job';
COMMENT ON COLUMN DEC_JOB_FOTO.CD_SCHED_DAYOFMONTH_FOTO IS 'Campo ''giorno del mese'' nella schedulazione del job';
COMMENT ON COLUMN DEC_JOB_FOTO.CD_SCHED_MONTH_FOTO IS 'Campo ''mese'' nella schedulazione del job';
COMMENT ON COLUMN DEC_JOB_FOTO.CD_SCHED_DAYOFWEEK_FOTO IS 'Campo ''giorno della settimana'' nella schedulazione del job';
COMMENT ON COLUMN DEC_JOB_FOTO.DT_PROSSIMA_ATTIVAZIONE_FOTO IS 'Quando il job verrà eseguito la prossima volta (se è attivo).';

-- changeset root:1780309613015-36
CREATE TABLE DIP_ATTRIB_RISULTATO (ID_ATTRIB_RISULTATO NUMBER NOT NULL, ID_RICERCA NUMBER NOT NULL, NM_ATTRIBUTO VARCHAR2(100 BYTE) NOT NULL, TI_DATO_ATTRIBUTO VARCHAR2(20 BYTE) NOT NULL, FL_ORDERBY CHAR(1 BYTE) NOT NULL, NI_ORDERBY NUMBER, TI_ORDERBY VARCHAR2(20 BYTE), CONSTRAINT PK_ATTR_RIS PRIMARY KEY (ID_ATTRIB_RISULTATO));

-- changeset root:1780309613015-37
CREATE TABLE DIP_CAMPO_RICERCA (ID_CAMPO_RICERCA NUMBER NOT NULL, ID_GRUPPO_CAMPI NUMBER NOT NULL, NM_CAMPO VARCHAR2(100 BYTE) NOT NULL, DS_CAMPO VARCHAR2(254 BYTE) NOT NULL, TI_DATO_CAMPO VARCHAR2(20 BYTE) NOT NULL, NI_RIGA_CAMPO NUMBER NOT NULL, NI_COLONNA_CAMPO NUMBER NOT NULL, CONSTRAINT PK_CAMPO_RIC PRIMARY KEY (ID_CAMPO_RICERCA));

-- changeset root:1780309613015-38
CREATE TABLE DIP_COMBINAZIONE_RICERCA (ID_COMBINAZIONE_RICERCA NUMBER NOT NULL, ID_RICERCA NUMBER NOT NULL, NM_NOME_COMBINAZIONE VARCHAR2(100 BYTE) NOT NULL, ID_STRUT NUMBER NOT NULL, ID_TIPO_DOC NUMBER, ID_TIPO_UNITA_DOC NUMBER, CONSTRAINT PK_COMB_RIC PRIMARY KEY (ID_COMBINAZIONE_RICERCA));

-- changeset root:1780309613015-39 splitStatements:true
CREATE TABLE DIP_DEC_JOB (ID_JOB NUMBER NOT NULL, NM_JOB VARCHAR2(100 BYTE) NOT NULL, TI_SCHED_JOB VARCHAR2(20 BYTE) NOT NULL, TI_SCOPO_JOB VARCHAR2(20 BYTE) NOT NULL, NM_NODO_ASSEGNATO VARCHAR2(100 BYTE), TI_STATO_TIMER VARCHAR2(20 BYTE), CD_SCHED_HOUR VARCHAR2(100 BYTE), CD_SCHED_MINUTE VARCHAR2(100 BYTE), CD_SCHED_DAYOFMONTH VARCHAR2(100 BYTE), CD_SCHED_MONTH VARCHAR2(100 BYTE), CD_SCHED_DAYOFWEEK VARCHAR2(100 BYTE), DT_PROSSIMA_ATTIVAZIONE date, FL_DATA_ACCURATA VARCHAR2(1 BYTE), DS_JOB VARCHAR2(200 BYTE), NM_AMBITO VARCHAR2(200 BYTE), NI_ORD_EXEC NUMBER, CONSTRAINT PK_JOB PRIMARY KEY (ID_JOB));
COMMENT ON TABLE DIP_DEC_JOB IS 'Tabella per configurare l''esecuzione dei timer. Utilizzata dai job su jboss e dalle sonde Zabbix';
COMMENT ON COLUMN DIP_DEC_JOB.NM_NODO_ASSEGNATO IS 'Nome del nodo del cluster su cui verrà eseguito il job';
COMMENT ON COLUMN DIP_DEC_JOB.TI_STATO_TIMER IS 'Stato del job: ATTIVO, INATTIVO o ESECUZIONE_SINGOLA';
COMMENT ON COLUMN DIP_DEC_JOB.CD_SCHED_HOUR IS 'Campo ''ora'' nella schedulazione del job';
COMMENT ON COLUMN DIP_DEC_JOB.CD_SCHED_MINUTE IS 'Campo ''minuto'' nella schedulazione del job';
COMMENT ON COLUMN DIP_DEC_JOB.CD_SCHED_DAYOFMONTH IS 'Campo ''giorno del mese'' nella schedulazione del job';
COMMENT ON COLUMN DIP_DEC_JOB.CD_SCHED_MONTH IS 'Campo ''mese'' nella schedulazione del job';
COMMENT ON COLUMN DIP_DEC_JOB.CD_SCHED_DAYOFWEEK IS 'Campo ''giorno della settimana'' nella schedulazione del job';
COMMENT ON COLUMN DIP_DEC_JOB.DT_PROSSIMA_ATTIVAZIONE IS 'Quando il job verrà eseguito la prossima volta (se è attivo).';

-- changeset root:1780309613015-40
CREATE TABLE DIP_DEF_ATTRIBUTO (ID_DEF_ATTRIBUTO NUMBER NOT NULL, ID_ATTRIB_RISULTATO NUMBER NOT NULL, ID_STRUT NUMBER NOT NULL, TI_DEF_ATTRIB VARCHAR2(20 BYTE) NOT NULL, ID_ATTRIB_DATI_SPEC NUMBER, NM_DATO_PROFILO VARCHAR2(100 BYTE), CD_QUERY_CALC VARCHAR2(1000 BYTE), CONSTRAINT PK_DEF_ATTR PRIMARY KEY (ID_DEF_ATTRIBUTO));

-- changeset root:1780309613015-41
CREATE TABLE DIP_DEF_ATTRIBUTO_BAK (ID_DEF_ATTRIBUTO NUMBER NOT NULL, ID_ATTRIB_RISULTATO NUMBER NOT NULL, ID_STRUT NUMBER NOT NULL, TI_DEF_ATTRIB VARCHAR2(20 BYTE) NOT NULL, ID_ATTRIB_DATI_SPEC NUMBER, NM_DATO_PROFILO VARCHAR2(100 BYTE), CD_QUERY_CALC VARCHAR2(1000 BYTE));

-- changeset root:1780309613015-42
CREATE TABLE DIP_ELEMENTO_DETTAGLIO (ID_ELEMENTO_DETTAGLIO NUMBER NOT NULL, ID_GRUPPO_DETTAGLIO NUMBER NOT NULL, NI_RIGA_ELEMENTO NUMBER NOT NULL, NI_COLONNA_ELEMENTO NUMBER NOT NULL, DS_ELEMENTO_DETTAGLIO VARCHAR2(255 BYTE) NOT NULL, ID_ATTRIB_RISULTATO NUMBER, FL_VISIBILE CHAR(1 BYTE) DEFAULT '1' NOT NULL, CONSTRAINT PK_DIP_ELEMENTO_DETTAGLIO PRIMARY KEY (ID_ELEMENTO_DETTAGLIO));

-- changeset root:1780309613015-43
CREATE TABLE DIP_ELEMENTO_LISTA (ID_ELEMENTO_LISTA NUMBER NOT NULL, NI_NUM_ORDINE NUMBER NOT NULL, DS_ELEMENTO_LISTA VARCHAR2(254 BYTE) NOT NULL, FL_VISIBILE CHAR(1 BYTE) NOT NULL, ID_ATTRIB_RISULTATO NUMBER, CONSTRAINT PK_LIS_RES PRIMARY KEY (ID_ELEMENTO_LISTA));

-- changeset root:1780309613015-44
CREATE TABLE DIP_ELEMENTO_LISTA_BAK (ID_ELEMENTO_LISTA NUMBER NOT NULL, NI_NUM_ORDINE NUMBER NOT NULL, DS_ELEMENTO_LISTA VARCHAR2(254 BYTE) NOT NULL, FL_VISIBILE CHAR(1 BYTE) NOT NULL, ID_ATTRIB_RISULTATO NUMBER);

-- changeset root:1780309613015-45
CREATE TABLE DIP_FILTRO_RICERCA (ID_FILTRO_RICERCA NUMBER NOT NULL, ID_COMBINAZIONE_RICERCA NUMBER NOT NULL, TI_TIPO_FILTRO VARCHAR2(20 BYTE) NOT NULL, NM_FILTRO_RICERCA VARCHAR2(100 BYTE) NOT NULL, FL_STATICO CHAR(1 BYTE) NOT NULL, ID_CAMPO_RICERCA NUMBER, ID_ATTRIB_DATI_SPEC NUMBER, TI_DATO_FILTRO VARCHAR2(20 BYTE) NOT NULL, CONSTRAINT PK_FILTRO_RIC PRIMARY KEY (ID_FILTRO_RICERCA));

-- changeset root:1780309613015-46
CREATE TABLE DIP_GRUPPO_CAMPI (ID_GRUPPO_CAMPI NUMBER NOT NULL, ID_RICERCA NUMBER NOT NULL, NM_GRUPPO VARCHAR2(100 BYTE) NOT NULL, DS_GRUPPO VARCHAR2(254 BYTE) NOT NULL, NI_RIGA_GRUPPO NUMBER NOT NULL, NI_COLONNA_GRUPPO NUMBER NOT NULL, CONSTRAINT PK_GRP_CAMPI PRIMARY KEY (ID_GRUPPO_CAMPI));

-- changeset root:1780309613015-47
CREATE TABLE DIP_GRUPPO_DETTAGLIO (ID_GRUPPO_DETTAGLIO NUMBER NOT NULL, ID_RICERCA NUMBER NOT NULL, NM_GRUPPO_DETTAGLIO VARCHAR2(100 BYTE) NOT NULL, NI_RIGA_GRUPPO NUMBER NOT NULL, NI_COLONNA_GRUPPO NUMBER NOT NULL, DS_GRUPPO_DETTAGLIO VARCHAR2(255 BYTE) NOT NULL, CONSTRAINT PK_DIP_GRUPPO_DETTAGLIO PRIMARY KEY (ID_GRUPPO_DETTAGLIO));

-- changeset root:1780309613015-48
CREATE TABLE DIP_QUERY_WITH (ID_QUERY_WITH NUMBER NOT NULL, ID_RICERCA NUMBER NOT NULL, NM_QUERY_WITH VARCHAR2(100 BYTE) NOT NULL, DL_QUERY_WITH VARCHAR2(1000 BYTE) NOT NULL, NI_ORD_WITH NUMBER NOT NULL, CONSTRAINT PK_QRY_WITH PRIMARY KEY (ID_QUERY_WITH));

-- changeset root:1780309613015-49
CREATE TABLE DIP_RICERCA (ID_RICERCA NUMBER NOT NULL, NM_RICERCA VARCHAR2(100 BYTE) NOT NULL, DS_RICERCA VARCHAR2(254 BYTE) NOT NULL, TI_TIPO_RECUPERO VARCHAR2(20 BYTE) NOT NULL, TI_TIPO_PRESENTAZIONE VARCHAR2(20 BYTE) NOT NULL, NI_RES_LIMIT NUMBER NOT NULL, NM_ENTRY_MENU VARCHAR2(100 BYTE) NOT NULL, TI_STATO_RICERCA VARCHAR2(20 BYTE) DEFAULT 'COMPLETA' NOT NULL, CONSTRAINT PK_DIP_RIC PRIMARY KEY (ID_RICERCA));

-- changeset root:1780309613015-50
CREATE TABLE DIP_SERVER (ID_SERVER NUMBER NOT NULL, CD_SERVER VARCHAR2(100 BYTE) NOT NULL, FL_DA_ALLINEARE CHAR(1 BYTE) DEFAULT 'N', CONSTRAINT PK_SERVER PRIMARY KEY (ID_SERVER));

-- changeset root:1780309613015-51
CREATE TABLE DIP_SYNCRO_ARO (ID_SYNCRO_ARO NUMBER NOT NULL, ID_STRUT NUMBER NOT NULL, DT_ULTIMA_DATA_ELAB date NOT NULL, NI_UD_SINCRO NUMBER NOT NULL, NI_DOC_SINCRO NUMBER NOT NULL, NI_UD_ANNUL NUMBER NOT NULL, NI_DOC_ANNUL NUMBER NOT NULL, CONSTRAINT PK_SYNC_ARO PRIMARY KEY (ID_SYNCRO_ARO));

-- changeset root:1780309613015-52
CREATE TABLE DIP_TIPO_DATO_PROFILO (ID_TIPO_DATO_PROFILO NUMBER NOT NULL, NM_TIPO_DATO_PROFILO VARCHAR2(25 BYTE) NOT NULL, TI_ORIGINE_DATO_PROFILO VARCHAR2(20 BYTE) NOT NULL, DT_ISTITUZ date NOT NULL, NM_COLONNA_DB VARCHAR2(100 BYTE) NOT NULL, TI_DATO_PROFILO VARCHAR2(20 BYTE) NOT NULL, TIPO_CONVERSIONE VARCHAR2(15 BYTE), CONSTRAINT PK_TI_DATO_PROFILO PRIMARY KEY (ID_TIPO_DATO_PROFILO));

-- changeset root:1780309613015-53
CREATE TABLE DIP_USO_WITH (ID_USO_WITH NUMBER NOT NULL, ID_DEF_ATTRIBUTO NUMBER NOT NULL, ID_QUERY_WITH NUMBER NOT NULL, CONSTRAINT PK_USO_WITH PRIMARY KEY (ID_USO_WITH));

-- changeset root:1780309613015-54
CREATE TABLE DIP_VALORE_COMBO (ID_VALORE_COMBO NUMBER NOT NULL, ID_CAMPO_RICERCA NUMBER NOT NULL, NM_VALORE_COMBO VARCHAR2(250 BYTE) NOT NULL, CD_VALORE_COMBO VARCHAR2(150 BYTE) NOT NULL, CONSTRAINT PK_VAL_COMBO PRIMARY KEY (ID_VALORE_COMBO));

-- changeset root:1780309613015-55
CREATE TABLE DIP_VALORE_PREDEFINITO (ID_VALORE_PREDEFINITO NUMBER NOT NULL, ID_FILTRO_RICERCA NUMBER NOT NULL, DL_VALORE VARCHAR2(4000 BYTE) NOT NULL, ID_REGISTRO_UNITA_DOC NUMBER, CONSTRAINT PK_VAL_PREDEF PRIMARY KEY (ID_VALORE_PREDEFINITO));

-- changeset root:1780309613015-56
CREATE TABLE EJB__TIMER__TBL (CREATIONTIMERAW NUMBER(19, 0) NOT NULL, BLOB BLOB, TIMERID VARCHAR2(256 BYTE) NOT NULL, CONTAINERID NUMBER(19, 0) NOT NULL, OWNERID VARCHAR2(256 BYTE), STATE NUMBER(*, 0) NOT NULL, PKHASHCODE NUMBER(*, 0) NOT NULL, INTERVALDURATION NUMBER(19, 0) NOT NULL, INITIALEXPIRATIONRAW NUMBER(19, 0) NOT NULL, LASTEXPIRATIONRAW NUMBER(19, 0) NOT NULL, SCHEDULE VARCHAR2(255 BYTE), APPLICATIONID NUMBER(19, 0) NOT NULL, CONSTRAINT PK_EJB__TIMER__TBL PRIMARY KEY (TIMERID));

-- changeset root:1780309613015-57
CREATE TABLE IAM_USER (ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL, CD_PSW VARCHAR2(100 BYTE) NOT NULL, NM_COGNOME_USER VARCHAR2(100 BYTE) NOT NULL, NM_NOME_USER VARCHAR2(100 BYTE) NOT NULL, FL_ATTIVO CHAR(1 BYTE) NOT NULL, DT_REG_PSW date NOT NULL, DT_SCAD_PSW date NOT NULL, FL_USER_ADMIN CHAR(1 BYTE) DEFAULT '0' NOT NULL, CD_SALT VARCHAR2(100 BYTE), CD_FISC VARCHAR2(16 BYTE), DS_EMAIL VARCHAR2(254 BYTE), FL_CONTR_IP CHAR(1 BYTE) DEFAULT '0' NOT NULL, TIPO_USER VARCHAR2(20 BYTE) DEFAULT 'PERSONA_FISICA' NOT NULL, CONSTRAINT PK_USR_IAM PRIMARY KEY (ID_USER_IAM));

-- changeset root:1780309613015-58
CREATE TABLE QRY_DOC_BY_VL_META_DT (ID_ATTRIB_DATI_SPEC NUMBER NOT NULL, ID_DOC NUMBER NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_VALORE TIMESTAMP(3) NOT NULL);

-- changeset root:1780309613015-59
CREATE TABLE QRY_DOC_BY_VL_META_NUM (ID_ATTRIB_DATI_SPEC NUMBER NOT NULL, ID_DOC NUMBER NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_VALORE NUMBER(19, 4) NOT NULL);

-- changeset root:1780309613015-60
CREATE TABLE QRY_DOC_BY_VL_META_STR (ID_ATTRIB_DATI_SPEC NUMBER NOT NULL, ID_DOC NUMBER NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_PREFISSO_VALORE VARCHAR2(1500 BYTE) NOT NULL, DL_VALORE VARCHAR2(4000 BYTE) NOT NULL);

-- changeset root:1780309613015-61
CREATE TABLE QRY_UD_BY_VL_DATO_PROFILO_DT (ID_STRUT NUMBER NOT NULL, TI_DATO_PROFILO VARCHAR2(15 BYTE) NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_VALORE TIMESTAMP(3) NOT NULL, ID_TIPO_UNITA_DOC NUMBER NOT NULL);

-- changeset root:1780309613015-62
CREATE TABLE QRY_UD_BY_VL_DATO_PROFILO_NUM (ID_STRUT NUMBER NOT NULL, TI_DATO_PROFILO VARCHAR2(15 BYTE) NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_VALORE NUMBER(19, 4) NOT NULL, ID_TIPO_UNITA_DOC NUMBER NOT NULL);

-- changeset root:1780309613015-63
CREATE TABLE QRY_UD_BY_VL_DATO_PROFILO_STR (ID_STRUT NUMBER NOT NULL, TI_DATO_PROFILO VARCHAR2(15 BYTE) NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_PREFISSO_VALORE VARCHAR2(1500 BYTE) NOT NULL, DL_VALORE VARCHAR2(4000 BYTE) NOT NULL, ID_TIPO_UNITA_DOC NUMBER NOT NULL);

-- changeset root:1780309613015-64
CREATE TABLE QRY_UD_BY_VL_META_DT (ID_ATTRIB_DATI_SPEC NUMBER NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_VALORE TIMESTAMP(3) NOT NULL);

-- changeset root:1780309613015-65
CREATE TABLE QRY_UD_BY_VL_META_NUM (ID_ATTRIB_DATI_SPEC NUMBER NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_VALORE NUMBER(19, 4) NOT NULL);

-- changeset root:1780309613015-66
CREATE TABLE QRY_UD_BY_VL_META_STR (ID_ATTRIB_DATI_SPEC NUMBER NOT NULL, ID_UNITA_DOC NUMBER NOT NULL, DL_PREFISSO_VALORE VARCHAR2(1500 BYTE) NOT NULL, DL_VALORE VARCHAR2(4000 BYTE) NOT NULL);

-- changeset root:1780309613015-67
CREATE TABLE STRUT_REFERENZIATE_PUG (ID_STRUT_REFERENZIATE_PUG NUMBER NOT NULL, ID_STRUT_FITTIZIA NUMBER NOT NULL, ID_STRUT_REALE NUMBER NOT NULL, CONSTRAINT PK_STRUT_REFERENZIATE_PUG PRIMARY KEY (ID_STRUT_REFERENZIATE_PUG));

-- changeset root:1780309613015-68
CREATE TABLE TMP_COMUNI (COMUNE VARCHAR2(100 BYTE));

-- changeset root:1780309613015-69
CREATE TABLE TMP_STRUT_REALE (ID_STRUT NUMBER NOT NULL);

-- changeset root:1780309613015-70
CREATE TABLE TMP_UNIONI_COMUNI (UNIONE_COMUNI VARCHAR2(100 BYTE));

-- changeset root:1780309613015-71
CREATE UNIQUE INDEX UN_ATTR_RIS ON DIP_ATTRIB_RISULTATO(ID_RICERCA, NM_ATTRIBUTO);

-- changeset root:1780309613015-72
ALTER TABLE DIP_ATTRIB_RISULTATO ADD CONSTRAINT UN_ATTR_RIS UNIQUE (ID_RICERCA, NM_ATTRIBUTO) USING INDEX UN_ATTR_RIS;

-- changeset root:1780309613015-73
CREATE UNIQUE INDEX UN_CAMPO_RIC ON DIP_CAMPO_RICERCA(ID_GRUPPO_CAMPI, NM_CAMPO);

-- changeset root:1780309613015-74
ALTER TABLE DIP_CAMPO_RICERCA ADD CONSTRAINT UN_CAMPO_RIC UNIQUE (ID_GRUPPO_CAMPI, NM_CAMPO) USING INDEX UN_CAMPO_RIC;

-- changeset root:1780309613015-75
CREATE UNIQUE INDEX UN_COMBO_NOME ON DIP_VALORE_COMBO(ID_CAMPO_RICERCA, NM_VALORE_COMBO);

-- changeset root:1780309613015-76
ALTER TABLE DIP_VALORE_COMBO ADD CONSTRAINT UN_COMBO_NOME UNIQUE (ID_CAMPO_RICERCA, NM_VALORE_COMBO) USING INDEX UN_COMBO_NOME;

-- changeset root:1780309613015-77
CREATE UNIQUE INDEX UN_COMBO_VALORE ON DIP_VALORE_COMBO(ID_CAMPO_RICERCA, CD_VALORE_COMBO);

-- changeset root:1780309613015-78
ALTER TABLE DIP_VALORE_COMBO ADD CONSTRAINT UN_COMBO_VALORE UNIQUE (ID_CAMPO_RICERCA, CD_VALORE_COMBO) USING INDEX UN_COMBO_VALORE;

-- changeset root:1780309613015-79
CREATE UNIQUE INDEX UN_COMB_RIC ON DIP_COMBINAZIONE_RICERCA(NM_NOME_COMBINAZIONE, ID_RICERCA);

-- changeset root:1780309613015-80
ALTER TABLE DIP_COMBINAZIONE_RICERCA ADD CONSTRAINT UN_COMB_RIC UNIQUE (NM_NOME_COMBINAZIONE, ID_RICERCA) USING INDEX UN_COMB_RIC;

-- changeset root:1780309613015-81
CREATE UNIQUE INDEX UN_DOC_BY_META_DT ON QRY_DOC_BY_VL_META_DT(ID_ATTRIB_DATI_SPEC, ID_DOC, ID_UNITA_DOC);

-- changeset root:1780309613015-82
ALTER TABLE QRY_DOC_BY_VL_META_DT ADD CONSTRAINT UN_DOC_BY_META_DT UNIQUE (ID_ATTRIB_DATI_SPEC, ID_DOC, ID_UNITA_DOC) USING INDEX UN_DOC_BY_META_DT;

-- changeset root:1780309613015-83
CREATE UNIQUE INDEX UN_DOC_BY_META_NUM ON QRY_DOC_BY_VL_META_NUM(ID_ATTRIB_DATI_SPEC, ID_DOC, ID_UNITA_DOC);

-- changeset root:1780309613015-84
ALTER TABLE QRY_DOC_BY_VL_META_NUM ADD CONSTRAINT UN_DOC_BY_META_NUM UNIQUE (ID_ATTRIB_DATI_SPEC, ID_DOC, ID_UNITA_DOC) USING INDEX UN_DOC_BY_META_NUM;

-- changeset root:1780309613015-85
CREATE UNIQUE INDEX UN_DOC_BY_META_STR ON QRY_DOC_BY_VL_META_STR(ID_ATTRIB_DATI_SPEC, ID_DOC, ID_UNITA_DOC);

-- changeset root:1780309613015-86
ALTER TABLE QRY_DOC_BY_VL_META_STR ADD CONSTRAINT UN_DOC_BY_META_STR UNIQUE (ID_ATTRIB_DATI_SPEC, ID_DOC, ID_UNITA_DOC) USING INDEX UN_DOC_BY_META_STR;

-- changeset root:1780309613015-87
CREATE UNIQUE INDEX UN_ELE_LIS ON DIP_ELEMENTO_LISTA(ID_ATTRIB_RISULTATO);

-- changeset root:1780309613015-88
ALTER TABLE DIP_ELEMENTO_LISTA ADD CONSTRAINT UN_ELE_LIS UNIQUE (ID_ATTRIB_RISULTATO) USING INDEX UN_ELE_LIS;

-- changeset root:1780309613015-89
CREATE UNIQUE INDEX UN_EL_DET_ATTR_RIS ON DIP_ELEMENTO_DETTAGLIO(ID_ATTRIB_RISULTATO);

-- changeset root:1780309613015-90
ALTER TABLE DIP_ELEMENTO_DETTAGLIO ADD CONSTRAINT UN_EL_DET_ATTR_RIS UNIQUE (ID_ATTRIB_RISULTATO) USING INDEX UN_EL_DET_ATTR_RIS;

-- changeset root:1780309613015-91
CREATE UNIQUE INDEX UN_EL_DET_RI_COL ON DIP_ELEMENTO_DETTAGLIO(ID_GRUPPO_DETTAGLIO, NI_RIGA_ELEMENTO, NI_COLONNA_ELEMENTO);

-- changeset root:1780309613015-92
ALTER TABLE DIP_ELEMENTO_DETTAGLIO ADD CONSTRAINT UN_EL_DET_RI_COL UNIQUE (ID_GRUPPO_DETTAGLIO, NI_RIGA_ELEMENTO, NI_COLONNA_ELEMENTO) USING INDEX UN_EL_DET_RI_COL;

-- changeset root:1780309613015-93
CREATE UNIQUE INDEX UN_FILTRO_RIC ON DIP_FILTRO_RICERCA(ID_COMBINAZIONE_RICERCA, TI_TIPO_FILTRO, NM_FILTRO_RICERCA, TI_DATO_FILTRO);

-- changeset root:1780309613015-94
ALTER TABLE DIP_FILTRO_RICERCA ADD CONSTRAINT UN_FILTRO_RIC UNIQUE (ID_COMBINAZIONE_RICERCA, TI_TIPO_FILTRO, NM_FILTRO_RICERCA, TI_DATO_FILTRO) USING INDEX UN_FILTRO_RIC;

-- changeset root:1780309613015-95
CREATE UNIQUE INDEX UN_GRP_CAMPI ON DIP_GRUPPO_CAMPI(NM_GRUPPO, ID_RICERCA);

-- changeset root:1780309613015-96
ALTER TABLE DIP_GRUPPO_CAMPI ADD CONSTRAINT UN_GRP_CAMPI UNIQUE (NM_GRUPPO, ID_RICERCA) USING INDEX UN_GRP_CAMPI;

-- changeset root:1780309613015-97
CREATE UNIQUE INDEX UN_GRP_CAMPI_RIG_COL ON DIP_GRUPPO_CAMPI(ID_RICERCA, NI_RIGA_GRUPPO, NI_COLONNA_GRUPPO);

-- changeset root:1780309613015-98
ALTER TABLE DIP_GRUPPO_CAMPI ADD CONSTRAINT UN_GRP_CAMPI_RIG_COL UNIQUE (ID_RICERCA, NI_RIGA_GRUPPO, NI_COLONNA_GRUPPO) USING INDEX UN_GRP_CAMPI_RIG_COL;

-- changeset root:1780309613015-99
CREATE UNIQUE INDEX UN_GRP_DETT ON DIP_GRUPPO_DETTAGLIO(ID_RICERCA, NM_GRUPPO_DETTAGLIO);

-- changeset root:1780309613015-100
ALTER TABLE DIP_GRUPPO_DETTAGLIO ADD CONSTRAINT UN_GRP_DETT UNIQUE (ID_RICERCA, NM_GRUPPO_DETTAGLIO) USING INDEX UN_GRP_DETT;

-- changeset root:1780309613015-101
CREATE UNIQUE INDEX UN_GRP_DETT_RI_COL ON DIP_GRUPPO_DETTAGLIO(ID_RICERCA, NI_COLONNA_GRUPPO, NI_RIGA_GRUPPO);

-- changeset root:1780309613015-102
ALTER TABLE DIP_GRUPPO_DETTAGLIO ADD CONSTRAINT UN_GRP_DETT_RI_COL UNIQUE (ID_RICERCA, NI_COLONNA_GRUPPO, NI_RIGA_GRUPPO) USING INDEX UN_GRP_DETT_RI_COL;

-- changeset root:1780309613015-103
CREATE UNIQUE INDEX UN_JOB ON DIP_DEC_JOB(NM_JOB);

-- changeset root:1780309613015-104
ALTER TABLE DIP_DEC_JOB ADD CONSTRAINT UN_JOB UNIQUE (NM_JOB) USING INDEX UN_JOB;

-- changeset root:1780309613015-105
CREATE UNIQUE INDEX UN_JOB_FOTO ON DEC_JOB_FOTO(NM_JOB_FOTO);

-- changeset root:1780309613015-106
ALTER TABLE DEC_JOB_FOTO ADD CONSTRAINT UN_JOB_FOTO UNIQUE (NM_JOB_FOTO) USING INDEX UN_JOB_FOTO;

-- changeset root:1780309613015-107
CREATE UNIQUE INDEX UN_LOG_JOB ON DIP_LOG_JOB(NM_JOB, TI_EVENTO, DT_EVENTO);

-- changeset root:1780309613015-108
ALTER TABLE DIP_LOG_JOB ADD CONSTRAINT UN_LOG_JOB UNIQUE (NM_JOB, TI_EVENTO, DT_EVENTO) USING INDEX UN_LOG_JOB;

-- changeset root:1780309613015-109
CREATE UNIQUE INDEX UN_PAR_APL ON DIP_PARAM_APPLIC(NM_PARAM_APPLIC);

-- changeset root:1780309613015-110
ALTER TABLE DIP_PARAM_APPLIC ADD CONSTRAINT UN_PAR_APL UNIQUE (NM_PARAM_APPLIC) USING INDEX UN_PAR_APL;

-- changeset root:1780309613015-111
CREATE UNIQUE INDEX UN_QRY_WITH ON DIP_QUERY_WITH(ID_RICERCA, NM_QUERY_WITH);

-- changeset root:1780309613015-112
ALTER TABLE DIP_QUERY_WITH ADD CONSTRAINT UN_QRY_WITH UNIQUE (ID_RICERCA, NM_QUERY_WITH) USING INDEX UN_QRY_WITH;

-- changeset root:1780309613015-113
CREATE UNIQUE INDEX UN_RIC ON DIP_RICERCA(NM_RICERCA);

-- changeset root:1780309613015-114
ALTER TABLE DIP_RICERCA ADD CONSTRAINT UN_RIC UNIQUE (NM_RICERCA) USING INDEX UN_RIC;

-- changeset root:1780309613015-115
CREATE UNIQUE INDEX UN_SERVER ON DIP_SERVER(CD_SERVER);

-- changeset root:1780309613015-116
ALTER TABLE DIP_SERVER ADD CONSTRAINT UN_SERVER UNIQUE (CD_SERVER) USING INDEX UN_SERVER;

-- changeset root:1780309613015-117
CREATE UNIQUE INDEX UN_STRUT_REFERENZIATE_PUG ON STRUT_REFERENZIATE_PUG(ID_STRUT_REALE);

-- changeset root:1780309613015-118
ALTER TABLE STRUT_REFERENZIATE_PUG ADD CONSTRAINT UN_STRUT_REFERENZIATE_PUG UNIQUE (ID_STRUT_REALE) USING INDEX UN_STRUT_REFERENZIATE_PUG;

-- changeset root:1780309613015-119
CREATE UNIQUE INDEX UN_SYNC_ARO ON DIP_SYNCRO_ARO(ID_STRUT);

-- changeset root:1780309613015-120
ALTER TABLE DIP_SYNCRO_ARO ADD CONSTRAINT UN_SYNC_ARO UNIQUE (ID_STRUT) USING INDEX UN_SYNC_ARO;

-- changeset root:1780309613015-121
CREATE UNIQUE INDEX UN_TI_DATO_PROFILO ON DIP_TIPO_DATO_PROFILO(NM_TIPO_DATO_PROFILO);

-- changeset root:1780309613015-122
ALTER TABLE DIP_TIPO_DATO_PROFILO ADD CONSTRAINT UN_TI_DATO_PROFILO UNIQUE (NM_TIPO_DATO_PROFILO) USING INDEX UN_TI_DATO_PROFILO;

-- changeset root:1780309613015-123
CREATE UNIQUE INDEX UN_UD_BY_META_DT ON QRY_UD_BY_VL_META_DT(ID_ATTRIB_DATI_SPEC, ID_UNITA_DOC);

-- changeset root:1780309613015-124
ALTER TABLE QRY_UD_BY_VL_META_DT ADD CONSTRAINT UN_UD_BY_META_DT UNIQUE (ID_ATTRIB_DATI_SPEC, ID_UNITA_DOC) USING INDEX UN_UD_BY_META_DT;

-- changeset root:1780309613015-125
CREATE UNIQUE INDEX UN_UD_BY_META_NUM ON QRY_UD_BY_VL_META_NUM(ID_ATTRIB_DATI_SPEC, ID_UNITA_DOC);

-- changeset root:1780309613015-126
ALTER TABLE QRY_UD_BY_VL_META_NUM ADD CONSTRAINT UN_UD_BY_META_NUM UNIQUE (ID_ATTRIB_DATI_SPEC, ID_UNITA_DOC) USING INDEX UN_UD_BY_META_NUM;

-- changeset root:1780309613015-127
CREATE UNIQUE INDEX UN_UD_BY_VL_DATO_PRO_NUM ON QRY_UD_BY_VL_DATO_PROFILO_NUM(ID_STRUT, TI_DATO_PROFILO, ID_UNITA_DOC);

-- changeset root:1780309613015-128
ALTER TABLE QRY_UD_BY_VL_DATO_PROFILO_NUM ADD CONSTRAINT UN_UD_BY_VL_DATO_PRO_NUM UNIQUE (ID_STRUT, TI_DATO_PROFILO, ID_UNITA_DOC) USING INDEX UN_UD_BY_VL_DATO_PRO_NUM;

-- changeset root:1780309613015-129
CREATE UNIQUE INDEX UN_UD_BY_VL_DATO_PRO_STR ON QRY_UD_BY_VL_DATO_PROFILO_STR(ID_STRUT, TI_DATO_PROFILO, ID_UNITA_DOC);

-- changeset root:1780309613015-130
ALTER TABLE QRY_UD_BY_VL_DATO_PROFILO_STR ADD CONSTRAINT UN_UD_BY_VL_DATO_PRO_STR UNIQUE (ID_STRUT, TI_DATO_PROFILO, ID_UNITA_DOC) USING INDEX UN_UD_BY_VL_DATO_PRO_STR;

-- changeset root:1780309613015-131
CREATE UNIQUE INDEX UN_USO_WITH ON DIP_USO_WITH(ID_DEF_ATTRIBUTO, ID_QUERY_WITH);

-- changeset root:1780309613015-132
ALTER TABLE DIP_USO_WITH ADD CONSTRAINT UN_USO_WITH UNIQUE (ID_DEF_ATTRIBUTO, ID_QUERY_WITH) USING INDEX UN_USO_WITH;

-- changeset root:1780309613015-133
CREATE UNIQUE INDEX UN_USR_IAM ON IAM_USER(NM_USERID);

-- changeset root:1780309613015-134
ALTER TABLE IAM_USER ADD CONSTRAINT UN_USR_IAM UNIQUE (NM_USERID) USING INDEX UN_USR_IAM;

-- changeset root:1780309613015-135
CREATE UNIQUE INDEX UN_VAL_PREDEF ON DIP_VALORE_PREDEFINITO(DL_VALORE, ID_FILTRO_RICERCA);

-- changeset root:1780309613015-136
ALTER TABLE DIP_VALORE_PREDEFINITO ADD CONSTRAINT UN_VAL_PREDEF UNIQUE (DL_VALORE, ID_FILTRO_RICERCA) USING INDEX UN_VAL_PREDEF;

-- changeset root:1780309613015-137
CREATE UNIQUE INDEX IDX_DOC_BY_META_DT ON QRY_DOC_BY_VL_META_DT(ID_ATTRIB_DATI_SPEC, DL_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-138
CREATE UNIQUE INDEX IDX_DOC_BY_META_NUM ON QRY_DOC_BY_VL_META_NUM(ID_ATTRIB_DATI_SPEC, DL_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-139
CREATE UNIQUE INDEX IDX_DOC_BY_META_STR ON QRY_DOC_BY_VL_META_STR(ID_ATTRIB_DATI_SPEC, DL_PREFISSO_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-140
CREATE UNIQUE INDEX IDX_UD_BY_META_DT ON QRY_UD_BY_VL_META_DT(ID_ATTRIB_DATI_SPEC, DL_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-141
CREATE UNIQUE INDEX IDX_UD_BY_META_NUM ON QRY_UD_BY_VL_META_NUM(ID_ATTRIB_DATI_SPEC, DL_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-142
CREATE UNIQUE INDEX IDX_UD_BY_META_STR ON QRY_UD_BY_VL_META_STR(ID_ATTRIB_DATI_SPEC, DL_PREFISSO_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-143
CREATE UNIQUE INDEX IDX_UD_BY_VL_DATO_PRO_DT ON QRY_UD_BY_VL_DATO_PROFILO_DT(ID_STRUT, TI_DATO_PROFILO, ID_TIPO_UNITA_DOC, DL_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-144
CREATE UNIQUE INDEX IDX_UD_BY_VL_DATO_PRO_NUM ON QRY_UD_BY_VL_DATO_PROFILO_NUM(ID_STRUT, TI_DATO_PROFILO, ID_TIPO_UNITA_DOC, DL_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-145
CREATE UNIQUE INDEX IDX_UD_BY_VL_DATO_PRO_STR ON QRY_UD_BY_VL_DATO_PROFILO_STR(ID_STRUT, TI_DATO_PROFILO, ID_TIPO_UNITA_DOC, DL_PREFISSO_VALORE, ID_UNITA_DOC);

-- changeset root:1780309613015-146
CREATE UNIQUE INDEX UN_UD_BY_META_STR ON QRY_UD_BY_VL_META_STR(ID_ATTRIB_DATI_SPEC, ID_UNITA_DOC);

-- changeset root:1780309613015-147
ALTER TABLE DIP_CAMPO_RICERCA ADD CONSTRAINT FK_CAMPO_RIC_GRP_CAMPI FOREIGN KEY (ID_GRUPPO_CAMPI) REFERENCES DIP_GRUPPO_CAMPI (ID_GRUPPO_CAMPI);

-- changeset root:1780309613015-148
ALTER TABLE DIP_COMBINAZIONE_RICERCA ADD CONSTRAINT FK_COMB_RIC_DIP_RICERCA FOREIGN KEY (ID_RICERCA) REFERENCES DIP_RICERCA (ID_RICERCA);

-- changeset root:1780309613015-149
ALTER TABLE DIP_ATTRIB_RISULTATO ADD CONSTRAINT FK_DIP_ATTRIB_RISULTATO FOREIGN KEY (ID_RICERCA) REFERENCES DIP_RICERCA (ID_RICERCA);

-- changeset root:1780309613015-150
ALTER TABLE DIP_DEF_ATTRIBUTO ADD CONSTRAINT FK_DIP_DEF_ATTR_ATTR_RIS FOREIGN KEY (ID_ATTRIB_RISULTATO) REFERENCES DIP_ATTRIB_RISULTATO (ID_ATTRIB_RISULTATO);

-- changeset root:1780309613015-151
ALTER TABLE DIP_ELEMENTO_DETTAGLIO ADD CONSTRAINT FK_DIP_ELE_DETT_DIP_GRP_DETT FOREIGN KEY (ID_GRUPPO_DETTAGLIO) REFERENCES DIP_GRUPPO_DETTAGLIO (ID_GRUPPO_DETTAGLIO);

-- changeset root:1780309613015-152
ALTER TABLE DIP_GRUPPO_DETTAGLIO ADD CONSTRAINT FK_DIP_GRUPPO_DETTAGLIO_RIC FOREIGN KEY (ID_RICERCA) REFERENCES DIP_RICERCA (ID_RICERCA);

-- changeset root:1780309613015-153
ALTER TABLE DIP_ELEMENTO_LISTA ADD CONSTRAINT FK_ELE_LIS_ATTR_RIS FOREIGN KEY (ID_ATTRIB_RISULTATO) REFERENCES DIP_ATTRIB_RISULTATO (ID_ATTRIB_RISULTATO);

-- changeset root:1780309613015-154
ALTER TABLE DIP_ELEMENTO_DETTAGLIO ADD CONSTRAINT FK_EL_DETT_ATTR_RIS FOREIGN KEY (ID_ATTRIB_RISULTATO) REFERENCES DIP_ATTRIB_RISULTATO (ID_ATTRIB_RISULTATO);

-- changeset root:1780309613015-155
ALTER TABLE DIP_FILTRO_RICERCA ADD CONSTRAINT FK_FILTRO_RIC_CAMPO_RIC FOREIGN KEY (ID_CAMPO_RICERCA) REFERENCES DIP_CAMPO_RICERCA (ID_CAMPO_RICERCA);

-- changeset root:1780309613015-156
ALTER TABLE DIP_FILTRO_RICERCA ADD CONSTRAINT FK_FILTRO_RIC_COMB_RIC FOREIGN KEY (ID_COMBINAZIONE_RICERCA) REFERENCES DIP_COMBINAZIONE_RICERCA (ID_COMBINAZIONE_RICERCA);

-- changeset root:1780309613015-157
ALTER TABLE DIP_GRUPPO_CAMPI ADD CONSTRAINT FK_GRP_CAMPI_RIC FOREIGN KEY (ID_RICERCA) REFERENCES DIP_RICERCA (ID_RICERCA);

-- changeset root:1780309613015-158
ALTER TABLE DIP_QUERY_WITH ADD CONSTRAINT FK_QRY_WITH_RIC FOREIGN KEY (ID_RICERCA) REFERENCES DIP_RICERCA (ID_RICERCA) ON DELETE CASCADE;

-- changeset root:1780309613015-159
ALTER TABLE DIP_USO_WITH ADD CONSTRAINT FK_USO_WITH_DEF_ATTR FOREIGN KEY (ID_DEF_ATTRIBUTO) REFERENCES DIP_DEF_ATTRIBUTO (ID_DEF_ATTRIBUTO);

-- changeset root:1780309613015-160
ALTER TABLE DIP_USO_WITH ADD CONSTRAINT FK_USO_WITH_QRY FOREIGN KEY (ID_QUERY_WITH) REFERENCES DIP_QUERY_WITH (ID_QUERY_WITH) ON DELETE CASCADE;

-- changeset root:1780309613015-161
ALTER TABLE DIP_VALORE_COMBO ADD CONSTRAINT FK_VAL_COMBO_CAMPO_RIC FOREIGN KEY (ID_CAMPO_RICERCA) REFERENCES DIP_CAMPO_RICERCA (ID_CAMPO_RICERCA);

-- changeset root:1780309613015-162
ALTER TABLE DIP_VALORE_PREDEFINITO ADD CONSTRAINT FK_VAL_PREDEF_FILTRO_RIC FOREIGN KEY (ID_FILTRO_RICERCA) REFERENCES DIP_FILTRO_RICERCA (ID_FILTRO_RICERCA);

